---
kind: pipeline
type: docker
name: backend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      repo: git.silkky.dev/ellie/piped-backend
      tags: latest,8614e6a0d824053a5812a17e25f8447107cba588
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: proxy

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./proxy
      dockerfile: ./proxy/Dockerfile
      repo: git.silkky.dev/ellie/piped-proxy
      tags: latest,76103eddc231e9c4522b6d65653beb0501131d80
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      repo: git.silkky.dev/ellie/piped-frontend
      tags: latest,1fbb37819c9b76b7d92b186e8de0d46030669327
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main
