---
kind: pipeline
type: docker
name: backend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      repo: git.silkky.dev/ellie/piped-backend
      tags: latest,5df388cfac78936943dfce00dbe2116b18df0703
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: proxy

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./proxy
      dockerfile: ./proxy/Dockerfile
      repo: git.silkky.dev/ellie/piped-proxy
      tags: latest,97dd7d40759847a3d42eca59c4e2334f55896930
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      repo: git.silkky.dev/ellie/piped-frontend
      tags: latest,aa8a3a6d168f257b052433035fabd8a22f1b8f3a
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main
