---
kind: pipeline
type: docker
name: Backend

steps:
  - name: Docker Build & Push
    image: plugins/docker
    settings:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      repo: git.silkky.dev/ellie/piped-backend
      tags: latest
      cache_from: git.silkky.dev/ellie/piped-backend:latest
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main
