---
kind: pipeline
type: docker
name: backend

steps:

  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      debug: true
      context: ./backend
      dockerfile: ./backend/Dockerfile
      repo: git.silkky.dev/ellie/piped-backend
      tags: latest
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main
