---
kind: pipeline
type: docker
name: backend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./backend
      dockerfile: ./backend/Dockerfile
      repo: git.silkky.dev/ellie/piped-backend
      tags: latest,f1ccd759ad2e2e7b77e2c1d7f04bf58123e3bc5f
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: proxy

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./proxy
      dockerfile: ./proxy/Dockerfile
      repo: git.silkky.dev/ellie/piped-proxy
      tags: latest,40d0cef1055eb2872f33102bb3d4815838d3eac0
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main

---
kind: pipeline
type: docker
name: frontend

steps:
  - name: build & push
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      repo: git.silkky.dev/ellie/piped-frontend
      tags: latest,65f7fca7c5e3c4629101825af63e759bb1b16427
      registry: git.silkky.dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_token

trigger:
  branch:
    - main
