networks:
  public:
    external: true
  backend:

volumes:
  database:
  
services:
  backend:
    image: ghcr.io/thesilkky/piped-backend:latest
    depends_on:
      - postgres
    restart: always
    hostname: piped-backend
    networks:
      - public
      - backend
    environment:
      - PORT=8080
      - HTTP_WORKERS=4
      - API_URL=https://piped-api.silkky.dev
      - PUBSUB_URL=https://piped-pubsub.silkky.dev
      - PROXY_PART=https://piped-proxy.silkky.dev
      - FRONTEND_URL=https://piped.silkky.dev
      - hibernate.connection.url=jdbc:postgresql://postgresql:5432/piped
      - hibernate.connection.driver_class=org.postgresql.Driver
      - hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - hibernate.connection.username=piped
      - hibernate.connection.password=${POSTGRESQL_PASSWORD}
      - COMPROMISED_PASSWORD_CHECK=true
      - DISABLE_LBRY=true

  proxy:
    image: ghcr.io/thesilkky/piped-proxy:latest
    restart: always
    hostname: piped-proxy
    networks:
      - public

  frontend:
    image: ghcr.io/thesilkky/piped-frontend:latest
    restart: always
    hostname: piped-frontend
    networks:
      - public

  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    hostname: postgres
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - database-password
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD_FILE=/run/secrets/database-password
