version: "3.8"

networks:
  public:
    external: true

volumes:
  database:
  
services:
  backend:
    image: thesilkky/piped-backend:latest
    hostname: piped-backend
    networks:
      - public
      - default
    environment:
      - PORT=8080
      - HTTP_WORKERS=4
      - API_URL=https://${API_HOST}
      - PUBSUB_URL=https://${PUBSUB_HOST}
      - PROXY_PART=https://${PROXY_HOST}
      - FRONTEND_URL=https://${FRONTEND_HOST}
      - hibernate.connection.url=jdbc:postgresql://postgres:5432/piped
      - hibernate.connection.driver_class=org.postgresql.Driver
      - hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - hibernate.connection.username=piped
      - hibernate.connection.password=${DATABASE_PASSWORD}
      - COMPROMISED_PASSWORD_CHECK=true
      - DISABLE_LBRY=true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.piped-backend.rule=Host(`${API_HOST}`)"
        - "traefik.http.routers.piped-backend.entryPoints=websecure"
        - "traefik.http.routers.piped-backend.tls.certResolver=le"
        - "traefik.http.routers.piped-backend.service=piped-backend"
        - "traefik.http.routers.piped-pubsub.rule=Host(`${PUBSUB_HOST}`) && Path(`/webhooks/pubsub`)"
        - "traefik.http.routers.piped-pubsub.entryPoints=websecure"
        - "traefik.http.routers.piped-pubsub.tls.certResolver=le"
        - "traefik.http.routers.piped-pubsub.service=piped-backend"
        - "traefik.http.services.piped-backend.loadbalancer.server.port=8080"

  proxy:
    image: thesilkky/piped-proxy:latest
    hostname: piped-proxy
    networks:
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.piped-proxy.rule=Host(`${PROXY_HOST}`)"
        - "traefik.http.routers.piped-proxy.entryPoints=websecure"
        - "traefik.http.routers.piped-proxy.tls.certResolver=le"
        - "traefik.http.routers.piped-proxy.service=piped-proxy"
        - "traefik.http.services.piped-proxy.loadbalancer.server.port=8080"

  frontend:
    image: thesilkky/piped-frontend:latest
    hostname: piped-frontend
    networks:
      - public
    environment:
      - API_HOST=${API_HOST}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.piped-frontend.rule=Host(`${FRONTEND_HOST}`)"
        - "traefik.http.routers.piped-frontend.entryPoints=websecure"
        - "traefik.http.routers.piped-frontend.tls.certResolver=le"
        - "traefik.http.routers.piped-frontend.service=piped-frontend"
        - "traefik.http.services.piped-frontend.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15.3-alpine3.18
    hostname: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
