networks:
  public:
    external: true
  backend:

volumes:
  database:
  
services:
  backend:
    image: ghcr.io/thesilkky/piped-backend:latest
    depends_on:
      - postgres
    restart: always
    hostname: piped-backend
    networks:
      - public
      - backend
    environment:
      - PORT=8080
      - HTTP_WORKERS=4
      - API_URL=https://${API_HOST}
      - PUBSUB_URL=https://${PUBSUB_HOST}
      - PROXY_PART=https://${PROXY_HOST}
      - FRONTEND_URL=https://${FRONTEND_HOST}
      - hibernate.connection.url=jdbc:postgresql://postgres:5432/piped
      - hibernate.connection.driver_class=org.postgresql.Driver
      - hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - hibernate.connection.username=piped
      - hibernate.connection.password=${DATABASE_PASSWORD}
      - COMPROMISED_PASSWORD_CHECK=true
      - DISABLE_LBRY=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piped-backend.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.piped-backend.entryPoints=websecure"
      - "traefik.http.routers.piped-backend.tls.certResolver=le"
      - "traefik.http.routers.piped-backend.middlewares=tailscaleWhiteList@file"
      - "traefik.http.routers.piped-backend.service=piped-backend"
      - "traefik.http.routers.piped-pubsub.rule=Host(`${PUBSUB_HOST}`) && Path(`/webhooks/pubsub`)"
      - "traefik.http.routers.piped-pubsub.entryPoints=websecure"
      - "traefik.http.routers.piped-pubsub.tls.certResolver=le"
      - "traefik.http.routers.piped-pubsub.service=piped-backend"
      - "traefik.http.services.piped-backend.loadbalancer.server.port=8080"

  proxy:
    image: ghcr.io/thesilkky/piped-proxy:latest
    restart: always
    hostname: piped-proxy
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piped-proxy.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.piped-proxy.entryPoints=websecure"
      - "traefik.http.routers.piped-proxy.tls.certResolver=le"
      - "traefik.http.routers.piped-proxy.middlewares=tailscaleWhiteList@file"
      - "traefik.http.routers.piped-proxy.service=piped-proxy"
      - "traefik.http.services.piped-proxy.loadbalancer.server.port=8080"

  frontend:
    image: ghcr.io/thesilkky/piped-frontend:latest
    restart: always
    hostname: piped-frontend
    networks:
      - public
    environment:
      - API_HOST=${API_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.piped-frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.piped-frontend.entryPoints=websecure"
      - "traefik.http.routers.piped-frontend.tls.certResolver=le"
      - "traefik.http.routers.piped-frontend.middlewares=tailscaleWhiteList@file"
      - "traefik.http.routers.piped-frontend.service=piped-frontend"
      - "traefik.http.services.piped-frontend.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    hostname: postgres
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
