name: Docker

on:
  push:
    paths-ignore:
      - "**.md"
      - "**/.gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  backend:
    uses: thesilkky/workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: thesilkky/piped-backend
      context: ./backend
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  proxy:
    uses: thesilkky/workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: thesilkky/piped-proxy
      context: ./proxy
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  frontend:
    uses: thesilkky/workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: thesilkky/piped-frontend
      context: ./frontend
      platforms: linux/amd64,linux/arm64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
